modLoader="javafml" #mandatory
license="MIT"
loaderVersion="[32,)" #mandatory
[[mods]] #mandatory
modId="lowocalization" #mandatory
version="${file.jarVersion}" #mandatory
displayName="lOwOcalizati\u03C9n" #mandatory
credits="Thank you Partonetrain for the wonderful idea." #optional
authors="Eutro" #optional
description="A mod that OwOifies any attempts to localise a string."
