name: Java CI

on:
  push:
    paths:
      - 'gradle.properties'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Get file name
        run: |
          echo "::set-output name=file_path::$(ls build/libs/*fabric.jar)"
          echo "::set-output name=versions::$(head -1 .game_versions.txt)"
        id: var

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v2
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: 378417
          game_endpoint: minecraft
          file_path: ${{ steps.var.outputs.file_path }}
          changelog: See recent commits [here](https://github.com/${{ github.repository }}/commits/${{ github.sha }}).
          changelog_type: markdown
          game_versions: ${{ steps.var.outputs.versions }}
          release_type: release