name: Java CI

on:
  push:
    paths:
      - 'gradle.properties'

jobs:
  build:
    name: "Build and publish ${{ matrix.loader }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        loader: [ "Forge", "Fabric" ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'Xplat/build.gradle', '${{ matrix.loader }}/build.gradle') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Get file name
        run: |
          echo "::set-output name=file_path::$(find ./${{ matrix.loader }}/build/libs/ -name "*.jar" | grep '[0-9]\.jar')"
          echo "::set-output name=versions::$(head -1 ./${{ matrix.loader }}/.game_versions.txt)"
        id: var

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v2
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: 378417
          game_endpoint: minecraft
          file_path: ${{ steps.var.outputs.file_path }}
          changelog: See recent commits [here](https://github.com/${{ github.repository }}/commits/${{ github.sha }}).
          changelog_type: markdown
          game_versions: ${{ steps.var.outputs.versions }}
          release_type: release