name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'gradle.properties'

jobs:
  build:
    name: "Build and publish ${{ matrix.loader }}"
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[no ci]') == false
    strategy:
      matrix:
        loader: [ "Forge", "Fabric" ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache
        uses: actions/cache@v1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ matrix.loader }}-${{ hashFiles('**/build.gradle', '**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :${{ matrix.loader }}:build --no-daemon

      - name: Get file name
        run: |
          echo "::set-output name=file_path::$(find ./${{ matrix.loader }}/build/libs/ -name "*.jar" | grep '[0-9]\.jar')"
          echo "::set-output name=versions::$(head -1 ./${{ matrix.loader }}/.game_versions.txt)"
        id: var

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v2
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: 378417
          game_endpoint: minecraft
          file_path: ${{ steps.var.outputs.file_path }}
          changelog: See recent commits [here](https://github.com/${{ github.repository }}/commits/${{ github.sha }}).
          changelog_type: markdown
          game_versions: ${{ steps.var.outputs.versions }}
          release_type: release
